ci: trying to print logs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,24 +101,9 @@ jobs:
         # $ chmod +x ./scripts/local-aws-setup.sh
         run: ./scripts/local-aws-setup.sh
 
+        # Print the logs if the tests fail
       - name: Run Hurl Tests
-        run: npm run test:integration
-        continue-on-error: true # This ensures the job doesn't fail immediately if the tests fail
-
-      - name: Capture Logs from AWS Services if Tests Fail
-        if: failure() # Only run this if the integration tests failed
-        run: |
-          echo "Fetching Docker logs for LocalStack container"
-          docker logs $(docker ps -q --filter "name=localstack") || echo "No LocalStack logs found"
-
-          echo "Fetching Docker logs for DynamoDB Local container"
-          docker logs $(docker ps -q --filter "name=dynamodb-local") || echo "No DynamoDB Local logs found"
-
-      - name: Capture Logs from the Application if Tests Fail
-        if: failure() # Only run this if the integration tests failed
-        run: |
-          echo "Fetching application logs"
-          docker logs $(docker ps -q --filter "name=fragments") || echo "No server logs found"
+        run: npm run test:integration || (docker compose logs; exit 1)
 
   docker-hub:
     name: Build and Push to Docker Hub
